#dev
sudo docker run -it -d \
-p 3306:3306 \
--name maze \
--restart=unless-stopped \
-v /store/data/maze/db:/var/lib/mysql \
-e MYSQL_RANDOM_ROOT_PASSWORD=true \
-e MYSQL_DATABASE=maze \
-e MYSQL_USER=db \
-e MYSQL_PASSWORD=123 \
mariadb


#test
sudo docker run -it -d \
-p 3306:3306 \
--name maze-db \
--restart=unless-stopped \
-v /store/data/maze/db:/var/lib/mysql \
-e MYSQL_ROOT_PASSWORD=123 \
-e MYSQL_DATABASE=maze \
-e MYSQL_USER=db \
-e MYSQL_PASSWORD=123 \
hypriot/rpi-mysql